### ISSUE TITLE
Notification when a bet is added?

### ISSUE THREAD

**Issue by sword134** [Lisandro79/BeatTheBookie#17] opened 2020-08-07 16:54 UTC
Hello, first of all thank you for the amazing dashboard! I've been working with Kelly algorithms for the past few days now but have been unable to find a proper webscraper for the betting sites I use, so huge applause to the fact that you are able to scrape the matches!

Since the source code for the dashboard isn't available would it perhaps be possible to implement a notification system? Either through a telegram bot, email or chrome desktop notifications?

Also I have 1 more request, would it be possible for you to also list the mean/median probs for the other outcomes aswel? That way one could manually (excel) calculate the 1/(prob-0,05) and check if it matches one selves bookmakers.

**Comment by Lisandro79** [comment] 2020-08-08 09:23
Hi @sword134 ,

We have no time at the moment to implement a notification system. However, another user created this Telegram bot a while ago: https://t.me/BeatTheBookieOpportunities (not sure if this still active).

I am not sure I understand your request. The dashboard shows the opportunities for one result (e.g., home win). It provides you with the mean odds across bookmakers and the mispriced value that a specific bookmaker is offering. You can estimate the threshold from those mean odds.

Hope this helps

**Comment by sword134** [comment] 2020-08-08 10:21
@Lisandro79 in order to calculate the real probabilities you need all 3 mean odds.
The formula for calculating the implied probability is (1/odds(i))*100 where i is odds for 1, x and 2, that way you get three values.

Example the mean bookmaker odds are 3,2 for 1, 3,5 for x and 1,99 for 2. The implied probabilities will then be 31,25% 28,57% and 50,25%. If we sum these implied probabilities together we get 110,7. This mean that the bookies are taking a 10,7% profit margin for this match (110,7-100). We can now calculate the real probabilities (the ones minus the bookie profit margin) by saying 31,25/110,7*100=28,39% for 1, 28,57/110,7*100=25,96% for x and 50,25/110,7*100=45,65% for 2.

Now that we have the 3 real probabilities for each outcome of the match we can calculate the fair odds. By saying 1(28,39/100)=3,52 for 1 and so on for the others giving 3,85 for x and 2,19 for 2.

I also just realised that you don't use the implied volatility for the calculation of 1/(p-0,05), however having already written up the process for calculating the real odds I will leave it here, perhaps someone will find it useful, so just ignore it.

However say I wanted to calculate the 1/(p-0,05) for the other odds (for some reason) then I would need the mean odds for 1, x and 2 respectively and not only the mean odds for the one that is deemed the most profitable (it's not really necessary but more of a safety measure to check that it all adds up together).

**Comment by sword134** [comment] 2020-08-08 10:30
@Lisandro79 Running an example of your formula on the following current opportunity bet (Floya vs. Halden), it doesn't add up?


Bettson: 1; 18,5 x; 8 and 2; 1,1.
The website recommends taking a bet on 2 with Bettson having the highest odds.
The mean for 2 is listed as 1,05, we get the probability by saying 1/1,05*100=95,24. We then input that probability into the formula described in your paper and get 1/(0,9524-0,05)=1,108. Then we check if 1,1>1,108 and get false. Im sure its just an rounding error but its still kind of weird to have it recommended still.

**Comment by Lisandro79** [comment] 2020-08-08 10:42
In our strategy, the search for mis-priced odds is independent for home, draw and away. In practice, one game could have two mis-priced odds, one for home win and one for away win. In that case, both odds would be acceptable for us (though we would only pick up one of them in real life).

As for you request, at the moment we do not have time to add these modifications to the dashboard. We are 100% devoted to other project. Sorry about this.

Regarding your calculation for Floya vs. Halden, I think you are right. It might be that the dashboard is showing the odds that are 5% higher than the median of the odds across bookmakers. If you use the median of the bookies (1.03) and the highest offered odds (1.1), then those odds are >5% our threshold. In any case, thanks for pointing this out. I will check the issue to see if it is a bug. 

Cheers

**Comment by sword134** [comment] 2020-08-08 10:45
@Lisandro79 one last thing.

Say we calculate the threshold for Floya vs Halden as 1,108 and one doesn't have access to Betsson would it be recommended to place a bet on say bet365 where the odds is 1,02? Naturally I think not but I just want confirmation that whatever bookie one uses must offer odds above the calculated threshold.

**Comment by Lisandro79** [comment] 2020-08-08 10:58
At the moment of writing this, the best odds for Floya vs Hayden for the away team are shown as 1.10 in the dashboard (not 1.08). The mean odds are at 1.04 and the median odds are at 1.03.

If you take the median odds (1.03), then anything equal or above 1.086 will work for our strategy, regardless of the Bookie who's offering those odds (it might be that more than one bookie have mis-priced odds). This is how I calculated it: `p_threshold_5% = (1/1.03) -  (1/1.086)`

"... and one doesn't have access to Betsson would it be recommended to place a bet on say bet365 where the odds is 1,02?"
The answer to this question is "definitely not recommended". Betting on odds priced lower than the mean / median odds + the 5% threshold (as in the case you mention) would go against our strategy.

**Comment by sword134** [comment] 2020-08-08 11:53
@Lisandro79 I wonder, did you ever try with an alpha level of 1% instead of the 5% that you currently use. Obviously you would get way less results, but what would the winrate and return look like? (God I wish I had the source code :P)

**Comment by sword134** [comment] 2020-08-08 14:55
If you do come around to working a bit on the website would you mind displaying the formula odds calculated in a column for each match? That way its easier to cross check if any of the other bookies offer odds that are above the threshold instead of having to input their odds in an excel formula and then checking if it exceeded the threshold.

**Comment by Lisandro79** [comment] 2020-08-11 01:07
Yes, we tried with different levels of alpha, from 1% to 10%, and found that the tradeoff between number of games and earnings was highest for 5%. If you are curious about the graphs, you could try that by yourself: we have uploaded all the historical data we used for the paper (closing odds and continuous odds). You can download the data and run the analysis.

"Also it seems the site is broken, its not ordering the bets by time and its picking bets almost a day into the future."
The games are not ordered by time, but the opportunities should not appear a day before the game. I will check that.

We are not working on this project anymore. Please do not expect any changes to the dashboard except for bug fixes. An often neglected issue with betting strategies is that they require a lot of time to develop the software to run and check them. And once you complete the system, and extra enormous amount of time is required to maintain it. Unfortunately, we do not have the time to do that anymore nor the money to hire someone to do it.

**Comment by sashml** [comment] 2020-08-12 08:40
> You can download the data and run the analysis.

I'd like to review, and deep dive. Is that possible to share some of your notebooks, or initial scripts?

> An often neglected issue with betting strategies is that they require a lot of time to develop the software to run and check them. And once you complete the system, and extra enormous amount of time is required to maintain it.

I think that's point of open source community to "help", and develop further the best ideas. So, don't hesitate to share your knowledge, internal results to help us contribute! Thank you.

**Comment by Lisandro79** [comment] 2020-08-12 09:08
@sashml. "I think that's point of open source community to "help", and develop further the best ideas. So, don't hesitate to share your knowledge, internal results to help us contribute! "

I really do not understand what you are talking about. All the scripts we've used for analysis have been uploaded into this repository, with a detailed explanation in the README... please check the "code" section.

**Comment by sword134** [comment] 2020-08-12 10:25
@Lisandro79 I think he meant the source code for the web page if I'm not mistaken

**Comment by Keokeo33** [comment] 2020-08-13 19:04
Where can i give you some results from my excel. Tommorow morning sao
paolo-fortatela x2

Στις Τρί, 11 Αυγ 2020, 04:08 ο χρήστης Orsai <notifications@github.com>
έγραψε:

**Comment by sword134** [comment] 2020-08-13 20:46
@Keokeo33 just post a google drive link here

**Comment by benn365** [comment] 2020-09-20 06:54
_Hi @Lisandro79 ,
I was really moved with your comment below.
Is there not a way to get us all to come together and get this project going? 
I know you've mentioned time and money to hire someone, do you need a novice like me to dedicate my time bc I'd gladly volunteer my time.
I think the project is beneficial and it should not be neglected as the dashboard hasn't shown games for several days now.


> We are not working on this project anymore. Please do not expect any changes to the dashboard except for bug fixes. An often neglected issue with betting strategies is that they require a lot of time to develop the software to run and check them. And once you complete the system, and extra enormous amount of time is required to maintain it. Unfortunately, we do not have the time to do that anymore nor the money to hire someone to do it.

**Comment by Keokeo33** [comment] 2020-09-20 07:05
Yes but from the time you show the dashboard at internet 143.19.84......
and you  show to people who want to win an ods wrong bets several times
your looser ...

Στις Κυρ, 20 Σεπ 2020, 09:55 ο χρήστης benn365 <notifications@github.com>
έγραψε:

**Comment by benn365** [comment] 2020-09-20 07:28
Hey Ingrate, your trolling is really becoming annoying.
I'm sorry you're longer with us with your incoherent ramblings but why would anyone put their time and money in a project only for freeloaders to whine and denigrate? 
Manchester Utd lost playing at home yesterday against Crystal Palace. 
Do you think anyone saw that coming? 
You stake bets AT YOUR OWN RISKS.

**Comment by benn365** [comment] 2020-09-20 07:45
@Lisandro79 If you don't mind dropping your PayPal id here, I'd be willing to chip in to help towards getting the dashboard running, no matter how little. Hopefully, sometime in the future, maybe a longtime commitment...will see.??? The dashboard needs to start running again. Thanks for your great work. And come to think of it, no one else thought of coming up with the idea of this project

**Comment by Keokeo33** [comment] 2020-09-20 07:49
Sorry lisandro i respect your job but my english are bad because i can
exlpain you how i said to you looser not with bad way but when your title
beat the bookie i was expected beat the bookie with there oodds and thats
my own believe the odds they give us can understant what will be the result
thanks...

Στις Κυρ, 20 Σεπ 2020, 10:29 ο χρήστης benn365 <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-20 07:52
Benn365 your follow an oasis which all the time you will see water but
never can taste it with this dashboard...

Στις Κυρ, 20 Σεπ 2020, 10:49 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by StefanBelo** [comment] 2020-09-20 08:54
I run such football strategy on betfair:

[http://bfexplorer.net/Articles/Content/469](http://bfexplorer.net/Articles/Content/469)

**Comment by Keokeo33** [comment] 2020-09-20 13:06
No sence my friend thats a stubility....

Στις Κυρ, 20 Σεπ 2020, 11:55 ο χρήστης Stefan Belopotocan <
notifications@github.com> έγραψε:

**Comment by Lisandro79** [comment] 2020-09-20 16:14
@benn365 , the dashboard is working now, it is showing the games again. 

One extra note: I perceive some urgency in your messages about the dashboard (the money offering, the work offer, the phrase "the dashboard needs to start running again"). Our dashboard was intended as a way to show that the strategy works, not as support for gamblers. I would like you to kindly consider this option: _we might remove the dashboard from the Internet anytime soon_. I don't think it's a good idea that people get too attached (financially or emotionally) to this dashboard. If the idea of not having access to the dashboard anymore sounds really bad to you (either for financial reasons or for any other reasons), that might be an indicator that you are giving too much importance to your betting.

Cheers

**Closed** 2020-09-20 16:14 UTC

**Comment by Keokeo33** [comment] 2020-09-20 18:01
Ορσαι who stubid can predict anything and dont play bet....?


Στις Κυρ, 20 Σεπ 2020, 19:15 ο χρήστης Orsai <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-20 19:16
And if you dont predict to play bets why your showing the results to
internet?keep it for your selves...

Στις Κυρ, 20 Σεπ 2020, 21:00 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-20 19:32
@Keokeo33 shut the fuck up, please just shut the fuck up...
I don't know if you are a troll or just really inept. This system isn't meant to predict bets, its meant to compare the odds given by different betting sites and find odds that are in the favour of the player.

**Comment by Keokeo33** [comment] 2020-09-20 19:36
Sorry loosers your dashboard is bullsheets like you looosers....

Στις Κυρ, 20 Σεπ 2020, 22:32 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-20 19:38
And something else close it from the internet please you destroy people
with your wrong bets looosers

Στις Κυρ, 20 Σεπ 2020, 22:35 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-20 19:47
@Keokeo33 let me guess, you lost a lot of money because you didn't understand how the dashboard was made? I actually enjoy the dashboard and have earned money using it, because I actually read how to use it. Don't blame the developers for making a tool that you don't understand. The real loser here is you, both money wise and intelligence wise.

**Comment by Keokeo33** [comment] 2020-09-21 06:41
I am not a gampler i dont speak or read good english and i didnt lost money
and i dont understand your project thats true so if you have a game oodds
sent me the result please my iq test is only 300 thanks....

Στις Κυρ, 20 Σεπ 2020, 22:47 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-21 07:05
@Keokeo33 lol. If you don't understand what you are reading then why are you trying to criticize it? I really think you should stop embarrassing yourself.

**Comment by Keokeo33** [comment] 2020-09-21 07:20
I am disapoint with your system just this i was expected better accurancy
from your system and is very tired study this thats i prefer sent me in my
email a match.....

Στις Δευ, 21 Σεπ 2020, 10:05 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-21 13:45
You see my friend sword35 you said that the match wadford u23 it was 1 but
the result comes whats meaning of you project i dont undestand why you show
wrong predicts maybe lisandro take money from bookmakers

Στις Δευ, 21 Σεπ 2020, 10:20 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-21 13:48
@Keokeo33 are you actually trolling or just braindead? How hard is it to understand that it wont be accurate 100% of the time, its meant to find odds that are in the favour of the player. Read the actual thesis...

**Comment by Keokeo33** [comment] 2020-09-21 13:52
Please sent me when you find a game....to undestand

Στις Δευ, 21 Σεπ 2020, 16:48 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-21 13:54
@Keokeo33 no I wont, you can read this instead https://arxiv.org/ftp/arxiv/papers/1710/1710.02824.pdf

**Comment by Keokeo33** [comment] 2020-09-21 13:54
Lets say macabi today is going to win?as the dashboard said...

Στις Δευ, 21 Σεπ 2020, 16:51 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-21 14:03
If you translate in greek i will be glad to read...

Στις Δευ, 21 Σεπ 2020, 16:54 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-21 14:04
My mind receive only simple ways

Στις Δευ, 21 Σεπ 2020, 17:02 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by sword134** [comment] 2020-09-21 14:20
@Keokeo33 not my problem.

**Comment by Keokeo33** [comment] 2020-09-21 14:51
I wait a taem for you.....

Στις Δευ, 21 Σεπ 2020, 17:20 ο χρήστης sword134 <notifications@github.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-21 15:03
I wait a team from y

Στις Δευ, 21 Σεπ 2020, 17:51 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-22 09:14
No matches today?

Στις Δευ, 21 Σεπ 2020, 18:03 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:

**Comment by Keokeo33** [comment] 2020-09-22 10:04
👍🤕

Στις Τρί, 22 Σεπ 2020, 12:13 ο χρήστης DOROS ALEXIOY <doros23@gmail.com>
έγραψε:
